# Настройки интерфейсов

# Общие настройки
[common]
no_invites_item = "PAPER"

# Интерфейс приглашений для игрока
[player_invites]
title = "&bПриглашения в кланы"
no_invites_text = "&cУ вас нет приглашений"
invite_item = "PAPER"
invite_name = "&3Вас пригласили в клан \"{clan_name}\""
invite_lore_accept = "&3Чтобы &aпринять &3приглашение в клан, нажмите &bЛКМ"
invite_lore_decline = "&3Чтобы &cотменить &3приглашение в клан, нажмите &bПКМ"
invite_accepted_message = "&aВы приняли приглашение в клан \"{clan_name}\""
invite_declined_message = "&cВы отклонили приглашение в клан \"{clan_name}\""

# Интерфейс отправленных приглашений для коммодоров и адмиралов
[sent_invites]
title = "&bОтправленные приглашения"
no_invites_text = "&cНет отправленных приглашений"
invite_item = "PLAYER_HEAD"
invite_name = "&b&l\"{player_name}\""
invite_lore_cancel = "&3Чтобы &cотменить &3приглашение в клан, нажмите &bЛКМ"
invite_cancelled_message = "&cВы отменили приглашение игрока \"{player_name}\" в клан"

[clan_shop]
title = "&bМагазин клана"

[clan_shop.treasury]
name = "&6Клановая казна: &e{balance} СтарКоинов"
lore = """
&3Пополнить казну клана
&3можно командой &b/clan donate [Сумма]
"""

[clan_shop.ads]
name = "&6Купить рекламу"
lore = """
&3Публикуя клановую рекламу
&3Вы сможете найти новых участников
&3Для своего клана, а так же
&3Оставить краткую информацию о клане
&7
&3Может использовать: &eАдмирал
"""

[clan_shop.motd]
name = "&6Клановое приветствие"
lore = """
&3Позволяет создать персональное
&3приветствие для участников
&3клана, при заходе на сервер
&7
&b/clan MOTD set [1-5] [Сообщение] &3-
&3Установить сообщение на
&3определённой линии
&7
&3Может использовать: &eАдмирал
&7
&3Стоимость: &b{cost} СтарКоинов
"""

[clan_shop.chat]
name = "&6Клановый чат"
lore = """
&3Даёт возможность писать в клан-чат
&b/clan chat [сообщение]
&b/cc [сообщение]
&7
&3Могут использовать: &eВсе
&7
&3Стоимость: &b{cost} СтарКоинов
"""

[clan_shop.party]
name = "&6Пати-призыв"
lore = """
&3Даёт возможность пригласить
&3всех участников клана в пати
&b/clan party
&7
&3Может использовать: &eАдмирал, Коммодор
&7
&3Стоимость: &b{cost} СтарКоинов
"""

[clan_shop.slots]
name = "&6Места для клана &e[{level} уровень]"
lore = """
&3Даёт дополнительные места 
&3для новых участников клана
&7
&3Мест куплено: &b{current}/{max}
&3Прокачка: &b+{upgrade} слотов
&7
&3Стоимость: &b{cost} СтарКоинов
"""

[clan_shop.upgrade]
name = "&6Повышение соклановцев"
lore = """
&3Позволяет &bповысить&3 или
&bпонизить&3 соклановца
&7
&b/clan promote [Ник] &3- Повысить
&b/clan demote [Ник] &3- Понизить
&7
&3Может использовать: &eАдмирал, Коммодор
&7
&3Стоимость: &b{cost} СтарКоинов
"""

[clan_shop.rename]
name = "&6Изменить название"
lore = """
&3Позволяет поменять название
&3клана на другое
&b/clan rename [Название]
&7
&3Может использовать: &eАдмирал
&7
&3Стоимость: {cost} СтарКоинов
"""

