[general]
no_permission = "&cУ вас недостаточно прав для выполнения данной команды!"
not_enough_money = "&cВам не хватает &b{amount} СтарКоинов&c."
not_enough_money_clan = "&cВ казне клана недостаточно средств. Не хватает: &b{amount} СтарКоинов"
not_in_clan = "&cВы не состоите в клане."
player_not_in_clan = "&cНа данный момент этот игрок не состоит в клане."
already_in_clan = "&cВы уже состоите в клане."
player_already_in_clan = "&cЭтот игрок уже состоит в клане."
player_not_found = "&cИгрок {player} не найден."
function_not_purchased = "&cФункция не приобретена. Купить её можно в /clan shop"
function_already_purchased = "&cФункция уже приобретена."
purchased_label = "&a&lКУПЛЕНО"

[pending]
timeout = "&cВремя на принятие решения по действию истекло."
no_tasks = "&cУ вас нет активных действий."
cancelled = "&eДействие успешно отменено!"

[clan]
header = "&bПомощь по команде /clan:"
name_is_not_match = "&cЗаданное наименование не соответствует требованиям."

[clan.create]
usage = "&b/clan create [имя] &7-&6 Создать клан"
no_permission = "&cСоздать клан может только &eКвазар&c."
success = "&aВы успешно создали клан {name}!"

[clan.rename]
usage = "&b/clan rename [новое имя] &7-&6 Переименовать клан"
no_permission = "&cПереименовать клан может только &eАдмирал&c."
request = """
&cВы уверены, что хотите переименовать клан {old_name}&c в {name}&c за &b{cost} СтарКоинов&c?
&f
&cЧтобы подтвердить смену названия напишите в чат &b/clan confirm&c, при отмене действия &b/clan recall&c.
"""
success = "&aВы успешно переименовали клан {old_name} в {name}!"

[clan.disband]
usage = "&b/clan disband &7-&6 Распустить клан"
no_permission = "&cРаспустить клан может только &eАдмирал&c."
request = """
&cВы уверены, что хотите расформировать клан {name}&c?
&f
&cЧтобы подтвердить удаление клана напишите в чат &b/clan confirm&c, при отмене действия &b/clan recall&c.
"""
success = "&aВы успешно распустили клан {name}!"

[clan.leave]
usage = "&b/clan leave &7-&6 Покинуть клан"
no_permission = "&cПокинуть клан может только &aРекрут&c."
request = """
&cВы уверены, что хотите выйти из клана {name}&c?
&f
&cЧтобы подтвердить выход из клана напишите в чат &b/clan confirm&c, при отмене действия &b/clan recall&c.
"""
success = "&aВы успешно покинули клан {name}!"

[clan.invite]
usage = "&b/clan invite [игрок] &7-&6 Пригласить игрока в клан"
no_permission = "&cПригласить игрока в клан может только &aКоммодор и выше&c."
success = "&aВы успешно пригласили игрока {player} в клан {clan}!"
received = "&aВы были приглашены в клан {clan} игроком {player}! &7(/clan invites)"
already_invited = "&cИгрок {player} уже приглашён в ваш клан."
max_slots = "&cВы не можете пригласить больше {max_slots} игроков в ваш клан."

[clan.cancel]
usage = "&b/clan cancel [игрок] &7-&6 Отменить предложение"
no_permission = "&cОтменить предложение может только &aСтаршина и выше&c."
success = "&aВы успешно отменили предложение на вступление в клан {clan} для игрока {player}!"
not_invited = "&cИгрок {player} не приглашён в ваш клан."
notify = "&b{executor} &cотменил предложение на вступление в клан {clan} для игрока {player}!"

[clan.kick]
usage = "&b/clan kick [игрок] &7-&6 Выгнать игрока из клана"
no_permission = "&cВыгнать игрока из клана может только &aКоммодор и выше&c."
success = "&aВы успешно выгнали игрока {player} из клана!"
notify = "&b{executor} &cисключил игрока &b{player} &cиз клана."
self = "&cВы не можете выгнать себя из клана."

[clan.invites]
usage = "&b/clan invites &7-&6 Открыть меню приглашений"

[clan.info]
usage = "&b/clan info (клан) &7-&6 Посмореть информацию о клане"
info = """
&6Информация о клане “{clan}&6”:
&3Адмирал клана: &b{owner}
&3Дата основания: &b{created_at}
&3Очки клана: &b{score}
&3Место в топе: &b{top_position}
&3Казна клана: &b{treasury}
&3Участники: {members}/{max_members}
&3Онлайн: &b{online}
"""

[clan.top]
usage = "&b/clan top &7-&6 Посмотреть топ кланов"
header = "&bТоп-15 лучших кланов:"
format = "&b{index}&7:&6 {clan} &7-&6 {score} очков"
footer = "&bВсего кланов: {count}"

[clan.score]
usage = "&b/clan score [игрок] &7-&6 Посмотреть количество клановых очков игрока"
no_scores = "&cУ вас нет клановых очков."
no_scores_other = "&cУ игрока {player} нет клановых очков."
player_not_found = "&cИгрок {player} не найден."
header = "&bКлановые очки игрока {player}:"
format = "&b{type}&7:&6 {score} очков"
footer = "&bВсего типов очков: {count}"

[clan.topmembers]
usage = "&b/clan topmembers [тип] &7-&6 Посмотреть топ лучших участников клана"
header = "&bТоп-10 лучших участников клана {clan} по {type} очкам:"
format = "&b{index}&7:&6 {player} &7-&6 {score} очков"
footer = "&bВсего участников: {count}"

[clan.antitopmembers]
usage = "&b/clan antitopmembers [тип] &7-&6 Посмотреть топ худших участников клана"
header = "&bТоп-10 худших участников клана {clan} по {type} очкам:"
format = "&b{index}&7:&6 {player} &7-&6 {score} очков"
footer = "&bВсего участников: {count}"

[clan.news]
usage = "&b/clan news &7-&6 Посмотреть последние новости клана"
header = "&bПоследние новости клана {clan}:"
footer = "&bПоказаны последние {count} новостей"

[clan.list]
usage = "&b/clan list (игрок) &7-&6 Посмотреть список игроков клана"
header = "&6Список игроков клана:"
format = "&6{role}: {names}"
footer = "&bВсего участников: {count}"

[clan.online]
usage = "&b/clan online (игрок) &7-&6 Посмотреть онлайн игроков клана"
header = "&6Соклановцы онлайн:"
format = "&6{role}: {names}"
footer = "&bВсего онлайн: {count}"

[clan.admiral]
usage = "&b/clan admiral [игрок] &7-&6 Передать Адмирала соклановцу"

[clan.donate]
usage = "&b/clan donate [сумма] &7-&6 Пополнить казну клана"
not_in_clan = "&cНужно состоять в клане, чтобы пополнить его казну."
not_enough_money = "&cНедостаточно СтарКоинов, чтобы выполнить это действие."
invalid_amount = "&cУкажите корректную сумму для пополнения казны."
success = "&3Казна клана пополнена на &b{amount} СтарКоинов"

[clan.shop]
usage = "&b/clan shop &7-&6 Открыть магазин клана"

[clan.promote]
usage = "&b/clan promote [игрок] &7-&6 Повысить звание соклановца"
self = "&cВы не можете повысить своё звание."

[clan.demote]
usage = "&b/clan demote [игрок] &7-&6 Понизить звание соклановца"
self = "&cВы не можете понизить своё звание."

[clan.chat]
usage = "&b/clan chat [сообщение] &7-&6 Написать сообщение в чат клана"
purchased = "&aВы успешно купили клановый чат за &b{cost} СтарКоинов"
format = "&8[&bКлан&8] &7{player}&8: &f{message}"
not_purchased = "&cВаш клан не приобрел функцию чата. Купить её можно в /clan shop"

[clan.party]
usage = "&b/clan party [сообщение] &7-&6 Отправить приглашение в тусовку всем соклановцам"

[clan.motd]
usage = "&b/clan motd <set/clear/check> &7-&6 Управление MOTD клана"
usage_set = "&b/clan motd set [1-5] [сообщение] &7-&6 Установить текст на конкретной строке в MOTD"
usage_clear = "&b/clan motd clear (1-5) &7-&6 Очистить текст на конкретной строке/весь текст в MOTD"
usage_check = "&b/clan motd check &7-&6 Предварительный просмотр MOTD клана"
purchased = "&aВы успешно купили MOTD для клана за &b{cost} СтарКоинов"

[clan.ad]
usage = "&b/clan ad &7-&6 Список кланов, которые купили рекламу"

[clan.ade]
usage = "&b/clan ade &7-&6 Отредактировать рекламу клана"

[clan.slots]
purchased = "&aВы успешно купили +{slots} слотов для клана за &b{cost} СтарКоинов"
max = "&cВы не можете купить больше слотов для клана."

# Административная секция

[aclan]
header = "&bПомощь по команде /aclan:"

[aclan.kick]
usage = "&b/aclan kick [игрок] &7-&6 Принудительно удалить участника из клана"

[aclan.disband]
usage = "&b/aclan disband [клан] &7-&6 Принудительно удалить участника из клана"

[aclan.clearmotd]
usage = "&b/aclan clearmotd [клан] &7-&6 Принудительно удалить участника из клана"

[aclan.promote]
usage = "&b/aclan promote [игрок] &7-&6 Принудительно повысить участника клана"

[aclan.demote]
usage = "&b/aclan demote [игрок] &7-&6 Принудительно понизить участника клана"

[aclan.shop]
usage = "&b/aclan shop [клан] &7-&6 Принудительно взаимодействовать с магазином клана, не тратя валюту"

[aclan.npc]
usage = "&b/aclan <spawn/remove/list/name/skin> &7-&6 Взаимодействие с рекламными NPC"

[aclan.ad]
usage = "&b/aclan ad <remove/invites> [клан] &7-&6 Взаимодействие с рекламой клана"