[general]
no_permission = "&cУ вас недостаточно прав для выполнения данной команды!"
not_enough_money = "&cВам не хватает &b{amount} СтарКоинов&c."
not_enough_money_clan = "&cВ казне клана недостаточно средств. Не хватает: &b{amount} СтарКоинов"
not_in_clan = "&cВы не состоите в клане."
player_not_in_clan = "&cНа данный момент этот игрок не состоит в клане."
already_in_clan = "&cВы уже состоите в клане."
player_already_in_clan = "&cЭтот игрок уже состоит в клане."
player_not_found = "&cИгрок {player} не найден."
function_not_purchased = "&cФункция не приобретена. Купить её можно в /clan shop"
function_already_purchased = "&cФункция уже приобретена."
purchased_label = "&a&lКУПЛЕНО"

[pending]
timeout = "&cВремя на принятие решения по действию истекло."
no_tasks = "&cУ вас нет активных действий."
cancelled = "&eДействие успешно отменено!"

[clan]
header = "&bПомощь по команде /clan:"
name_is_not_match = "&cЗаданное наименование не соответствует требованиям."

[clan.create]
usage = "&b/clan create [имя] &7-&6 Создать клан"
no_permission = "&cСоздать клан может только &eКвазар&c."
success = "&aВы успешно создали клан {name}!"

[clan.rename]
usage = "&b/clan rename [новое имя] &7-&6 Переименовать клан"
no_permission = "&cПереименовать клан может только &eАдмирал&c."
request = """
&cВы уверены, что хотите переименовать клан {old_name}&c в {name}&c за &b{cost} СтарКоинов&c?
&f
&cЧтобы подтвердить смену названия напишите в чат &b/clan confirm&c, при отмене действия &b/clan recall&c.
"""
success = "&aВы успешно переименовали клан {old_name} в {name}!"

[clan.disband]
usage = "&b/clan disband &7-&6 Распустить клан"
no_permission = "&cРаспустить клан может только &eАдмирал&c."
request = """
&cВы уверены, что хотите расформировать клан {name}&c?
&f
&cЧтобы подтвердить удаление клана напишите в чат &b/clan confirm&c, при отмене действия &b/clan recall&c.
"""
success = "&aВы успешно распустили клан {name}!"

[clan.leave]
usage = "&b/clan leave &7-&6 Покинуть клан"
no_permission = "&cПокинуть клан может только &aРекрут&c."
request = """
&cВы уверены, что хотите выйти из клана {name}&c?
&f
&cЧтобы подтвердить выход из клана напишите в чат &b/clan confirm&c, при отмене действия &b/clan recall&c.
"""
success = "&aВы успешно покинули клан {name}!"

[clan.invite]
usage = "&b/clan invite [игрок] &7-&6 Пригласить игрока в клан"
no_permission = "&cПригласить игрока в клан может только &aКоммодор и выше&c."
success = "&aВы успешно пригласили игрока {player} в клан {clan}!"
received = "&aВы были приглашены в клан {clan} игроком {player}! &7(/clan invites)"
already_invited = "&cИгрок {player} уже приглашён в ваш клан."
max_slots = "&cВы не можете пригласить больше {max_slots} игроков в ваш клан."

[clan.cancel]
usage = "&b/clan cancel [игрок] &7-&6 Отменить предложение"
no_permission = "&cОтменить предложение может только &aСтаршина и выше&c."
success = "&aВы успешно отменили предложение на вступление в клан {clan} для игрока {player}!"
not_invited = "&cИгрок {player} не приглашён в ваш клан."
notify = "&b{executor} &cотменил предложение на вступление в клан {clan} для игрока {player}!"

[clan.kick]
usage = "&b/clan kick [игрок] &7-&6 Выгнать игрока из клана"
no_permission = "&cВыгнать игрока из клана может только &aКоммодор и выше&c."
success = "&aВы успешно выгнали игрока {player} из клана!"
notify = "&b{executor} &cисключил игрока &b{player} &cиз клана."
self = "&cВы не можете выгнать себя из клана."

[clan.invites]
usage = "&b/clan invites &7-&6 Открыть меню приглашений"

[clan.info]
usage = "&b/clan info (клан) &7-&6 Посмореть информацию о клане"
info = """
&6Информация о клане “{clan}&6”:
&3Адмирал клана: &b{owner}
&3Дата основания: &b{created_at}
&3Очки клана: &b{score}
&3Место в топе: &b{top_position}
&3Казна клана: &b{treasury}
&3Участники: {members}/{max_members}
&3Онлайн: &b{online}
"""

[clan.top]
usage = "&b/clan top &7-&6 Посмотреть топ кланов"
header = "&bТоп-15 лучших кланов:"
format = "&b{index}&7:&6 {clan} &7-&6 {score} очков"
footer = "&bВсего кланов: {count}"

[clan.score]
usage = "&b/clan score [игрок] &7-&6 Посмотреть количество клановых очков игрока"
no_scores = "&cУ вас нет клановых очков."
no_scores_other = "&cУ игрока {player} нет клановых очков."
player_not_found = "&cИгрок {player} не найден."
header = "&bКлановые очки игрока {player}:"
format = "&b{type}&7:&6 {score} очков"
footer = "&bВсего типов очков: {count}"

[clan.topmembers]
usage = "&b/clan topmembers [тип] &7-&6 Посмотреть топ лучших участников клана"
header = "&bТоп-10 лучших участников клана {clan} по {type} очкам:"
format = "&b{index}&7:&6 {player} &7-&6 {score} очков"
footer = "&bВсего участников: {count}"

[clan.antitopmembers]
usage = "&b/clan antitopmembers [тип] &7-&6 Посмотреть топ худших участников клана"
header = "&bТоп-10 худших участников клана {clan} по {type} очкам:"
format = "&b{index}&7:&6 {player} &7-&6 {score} очков"
footer = "&bВсего участников: {count}"

[clan.news]
usage = "&b/clan news &7-&6 Посмотреть последние новости клана"
header = "&bПоследние новости клана {clan}:"
footer = "&bПоказаны последние {count} новостей"

[clan.list]
usage = "&b/clan list (игрок) &7-&6 Посмотреть список игроков клана"
header = "&6Список игроков клана:"
format = "&6{role}: {names}"
footer = "&bВсего участников: {count}"

[clan.online]
usage = "&b/clan online (игрок) &7-&6 Посмотреть онлайн игроков клана"
header = "&6Соклановцы онлайн:"
format = "&6{role}: {names}"
footer = "&bВсего онлайн: {count}"

[clan.admiral]
usage = "&b/clan admiral [игрок] &7-&6 Передать Адмирала соклановцу"
no_permission = "&cПередать Адмирала может только &eАдмирал&c."
self = "&cВы не можете передать Адмирала себе."
success = "&aВы успешно передали Адмирала соклановцу {player}!"

[clan.donate]
usage = "&b/clan donate [сумма] &7-&6 Пополнить казну клана"
not_in_clan = "&cНужно состоять в клане, чтобы пополнить его казну."
not_enough_money = "&cНедостаточно СтарКоинов, чтобы выполнить это действие."
invalid_amount = "&cУкажите корректную сумму для пополнения казны."
success = "&3Казна клана пополнена на &b{amount} СтарКоинов"

[clan.shop]
usage = "&b/clan shop &7-&6 Открыть магазин клана"

[clan.promote]
usage = "&b/clan promote [игрок] &7-&6 Повысить звание соклановца"
self = "&cВы не можете повысить своё звание."
not_enough_money = "&cУ вас недостаточно СтарКоинов для повышения соклановца."
success = "&aВы успешно повысили соклановца {player} до {role}!"

[clan.demote]
usage = "&b/clan demote [игрок] &7-&6 Понизить звание соклановца"
self = "&cВы не можете понизить своё звание."
success = "&aВы успешно понизили соклановца {player} до {role}!"

[clan.chat]
usage = "&b/clan chat [сообщение] &7-&6 Написать сообщение в чат клана"
purchased = "&aВы успешно купили клановый чат за &b{cost} СтарКоинов"
format = "&6[{clan}&6]&e {player}: {message}"
not_purchased = "&cФункция не приобретена. Купить её можно в /clan shop"

[clan.party]
usage = "&b/clan party [сообщение] &7-&6 Отправить приглашение в тусовку всем соклановцам"
purchased = "&aВы успешно купили пати-призыв за &b{cost} СтарКоинов"
not_purchased = "&cФункция не приобретена. Купить её можно в /clan shop"
no_permission = "&cДля ввода команды Вы должны быть &eКоммодором&c/&eАдмиралом"
success = "&aКоманда успешно использована"

[clan.motd]
usage = "&b/clan motd <set/clear/check> &7-&6 Управление MOTD клана"
usage_set = "&b/clan motd set [1-5] [сообщение] &7-&6 Установить текст на конкретной строке в MOTD"
usage_clear = "&b/clan motd clear (1-5) &7-&6 Очистить текст на конкретной строке/весь текст в MOTD"
usage_check = "&b/clan motd check &7-&6 Предварительный просмотр MOTD клана"
purchased = "&aВы успешно купили MOTD для клана за &b{cost} СтарКоинов"
not_purchased = "&cФункция не приобретена. Купить её можно в /clan shop"
no_permission = "&cВы должны быть &eАдмиралом &cклана, чтобы редактировать MOTD"
set_success = "&aСтрока {line} MOTD успешно установлена"
clear_success = "&aMOTD успешно очищен"
clear_line_success = "&aСтрока {line} MOTD успешно очищена"
header = "&6MOTD клана {clan}:"
empty = "&7MOTD пуст"

[clan.ad]
usage = "&b/clan ad &7-&6 Список кланов, которые купили рекламу"

[clan.ad.line]
usage = "&b/clan ad line <set/clear/check> &7-&6 Управление текстом рекламы клана"
usage_set = "&b/clan ad line set [1-20] [сообщение] &7-&6 Установить текст на конкретной строке в рекламе"
usage_clear = "&b/clan ad line clear (1-20) &7-&6 Очистить текст на конкретной строке/весь текст в рекламе"
usage_check = "&b/clan ad line check &7-&6 Предварительный просмотр текста рекламы клана"
set_success = "&aСтрока {line} рекламы успешно установлена"
clear_success = "&aТекст рекламы успешно очищен"
clear_line_success = "&aСтрока {line} рекламы успешно очищена"
header = "&6Текст рекламы клана {clan}:"
empty = "&7Текст рекламы пуст"

[clan.ade]
usage = "&b/clan ade &7-&6 Отредактировать рекламу клана"

[clan.slots]
purchased = "&aВы успешно купили +{slots} слотов для клана за &b{cost} СтарКоинов"
max = "&cВы не можете купить больше слотов для клана."

# Сообщения для рекламы кланов
[advertise]
created_success = "&aРеклама успешно создана! Она будет активна в течение &e{hours} часов&a. С баланса клана списано: &e{cost}"
created_error = "&cОшибка при создании рекламы. Попробуйте позже."
deleted_success = "&aРеклама успешно удалена!"
deleted_error = "&cОшибка при удалении рекламы. Попробуйте позже."
already_has_ad = "&cУ вашего клана уже есть активная реклама!"
no_active_ad = "&cУ вашего клана нет активной рекламы!"
not_enough_money = "&cНедостаточно средств в казне клана. Требуется: &e{cost}&c, у вас: &e{balance}"
text_updated = "&aТекст рекламы успешно обновлен!"
purchase_cancelled = "&cПокупка рекламы отменена."
delete_cancelled = "&cУдаление рекламы отменена."
join_type_changed = "&aТип присоединения изменен на: &e{type}"
error_updating = "&cПроизошла ошибка при обновлении рекламы. Попробуйте позже."
not_found = "&cРеклама не найдена. Возможно, она была удалена."

# Административная секция

[aclan]
header = "&bПомощь по команде /aclan:"

[aclan.kick]
usage = "&b/aclan kick [ник] &7-&6 Принудительно удалить участника из клана"
success = "&aВы успешно удалили игрока &e{player}&a из клана &e{clan}&a!"
notify = "&cАдминистратор &e{admin}&c принудительно удалил вас из клана!"

[aclan.disband]
usage = "&b/aclan disband [UUID] &7-&6 Принудительно удалить клан"
not_found = "&cКлан с идентификатором &e{identifier}&c не найден."
success = "&aВы успешно удалили клан &e{clan}&a!"

[aclan.clearmotd]
usage = "&b/aclan clearmotd [UUID] &7-&6 Принудительно очистить приветствие клана"
not_found = "&cКлан с идентификатором &e{identifier}&c не найден."
success = "&aВы успешно очистили приветствие клана &e{clan}&a!"

[aclan.demote]
usage = "&b/aclan demote [ник] &7-&6 Принудительно понизить участника клана"
already_lowest = "&cИгрок &e{player}&c уже имеет самое низкое звание!"
success = "&aВы успешно понизили игрока &e{player}&a с &e{old_role}&a до &e{new_role}&a!"
notify = "&cАдминистратор &e{admin}&c понизил ваше звание с &e{old_role}&c до &e{new_role}&c!"

[aclan.promote]
usage = "&b/aclan promote [ник] &7-&6 Принудительно повысить участника клана"
already_highest = "&cИгрок &e{player}&c уже имеет самое высокое звание!"
success = "&aВы успешно повысили игрока &e{player}&a с &e{old_role}&a до &e{new_role}&a!"
notify = "&cАдминистратор &e{admin}&c повысил ваше звание с &e{old_role}&c до &e{new_role}&c!"
admiral_demoted = "&cАдминистратор &e{admin}&c сместил вас с поста Адмирала! Новый Адмирал: &e{new_admiral}&c."

[aclan.shop]
usage = "&b/aclan shop [UUID] &7-&6 Открыть магазин клана"
not_found = "&cКлан с идентификатором &e{identifier}&c не найден."

[aclan.npc]
usage = "&b/aclan npc [spawn|remove|list|name|skin] &7-&6 Управление NPC"
citizens_not_found = "&cПлагин Citizens не установлен на сервере!"

[aclan.npc.spawn]
usage = "&b/aclan npc spawn [имя] &7-&6 Создать NPC с рекламой кланов"
success = "&aВы успешно создали NPC с именем &e{name}&a!"

[aclan.npc.remove]
usage = "&b/aclan npc remove [имя] &7-&6 Удалить NPC"
not_found = "&cNPC с именем &e{name}&c не найден."
success = "&aВы успешно удалили NPC с именем &e{name}&a!"

[aclan.npc.list]
usage = "&b/aclan npc list &7-&6 Просмотреть список всех NPC"
empty = "&cНа сервере нет NPC."
header = "&bСписок всех NPC:"
format = "&b{index}. &e{name} &7- &f{world} {x} {y} {z}"
footer = "&bВсего NPC: &e{count}"

[aclan.npc.name]
usage = "&b/aclan npc name [имя] &7-&6 Установить имя для всех NPC"
no_npcs = "&cНа сервере нет NPC."
success = "&aВы успешно установили имя &e{name}&a для &e{count}&a NPC!"

[aclan.npc.skin]
usage = "&b/aclan npc skin [скин] &7-&6 Установить скин для всех NPC"
no_npcs = "&cНа сервере нет NPC."
success = "&aВы успешно установили скин &e{skin}&a для &e{count}&a NPC!"

[aclan.rename]
usage = "&b/aclan rename [UUID] [новое имя] &7-&6 Принудительно переименовать клан"
not_found = "&cКлан с идентификатором &e{identifier}&c не найден."
success = "&aВы успешно переименовали клан &e{old_name}&a в &e{new_name}&a!"

[aclan.uuid]
usage = "&b/aclan uuid [ник] &7-&6 Узнать UUID клана игрока"
success = "&aИгрок &e{player}&a состоит в клане &e{clan}&a с UUID: &e{uuid}&a"

[aclan.ad]
usage = "&b/aclan ad [remove|invites] &7-&6 Управление рекламой клана"

[aclan.ad.remove]
usage = "&b/aclan ad remove [UUID] &7-&6 Принудительно удалить рекламу клана"
not_found = "&cКлан с идентификатором &e{identifier}&c не найден."
no_ad = "&cУ клана &e{clan}&c нет активной рекламы."
success = "&aВы успешно удалили рекламу клана &e{clan}&a!"

[aclan.ad.invites]
usage = "&b/aclan ad invites [UUID] &7-&6 Просмотреть заявки в клан"
not_found = "&cКлан с идентификатором &e{identifier}&c не найден."

[aclan.score]
usage = "&b/aclan score [add|remove|set|info] [ник] [режим] [количество] &7-&6 Управление очками игрока"
invalid_action = "&cНеверное действие. Используйте add, remove или set."
invalid_game_type = "&cНеверный тип игры. Доступные типы: &e{available_games}"
invalid_amount = "&cКоличество очков должно быть числом."
amount_must_be_positive = "&cКоличество очков должно быть положительным числом."
added = "&aВы успешно добавили &e{amount}&a очков в режиме &e{game_type}&a игроку &e{player}&a!"
removed = "&aВы успешно убавили &e{amount}&a очков в режиме &e{game_type}&a у игрока &e{player}&a!"
set = "&aВы успешно установили &e{amount}&a очков в режиме &e{game_type}&a игроку &e{player}&a!"
current = "&aТекущее количество очков игрока &e{player}&a в режиме &e{game_type}&a: &e{score}"
notify = "&cАдминистратор &e{admin}&c {action} вам &e{amount}&c очков в режиме &e{game_type}&c. Текущее количество: &e{current}"

[aclan.score.info]
usage = "&b/aclan score info [ник] &7-&6 Просмотр очков игрока"
no_scores = "&cУ игрока &e{player}&c нет очков."
header = "&6Очки игрока &e{player}&6:"
entry = "&3• &b{game_type}: &e{score}"
total = "&6Всего очков: &e{total}"

