[database]
host = "localhost"   # Хост
port = 3306          # Порт
user = "root"        # Пользователь
pass = "root"        # Пароль
data = "clans"       # База данных

[general]
action_expire = 30  # Время (в секундах), после которого действие отменится.
party_command = "/party invite {player}"

[pricing]
create = 70_000.0     # Создание клана
rename = 50_000.0     # Переименование клана
promote = 25_000.0    # Повышение соклановца
clan_chat = 20_000.0  # Клановый чат
clan_motd = 50_000.0  # Клановое приветствие
party = 20_000.0      # Пати-призыв

[permissions]
create = "clan.create"   # Право на создание клана
admin = "clans.admin"    # Право на использование административных команд

[restrictions]
min_name_length = 3    # Минимальное кол-во символов в имени клана (только буквы, без учёта цвета)
max_name_length = 12   # Максимальное кол-во символов в имени клана (только буквы, без учёта цвета)

[actions]             # RECRUIT, SENIOR, COMMODORE, ADMIRAL
rename = "ADMIRAL"    # Минимальный ранг участника клана, который позволяет переименовать клан
disband = "ADMIRAL"   # Минимальный ранг участника клана, который позволяет расформировать клан
invite = "SENIOR"     # Минимальный ранг участника клана, который позволяет пригласить игрока в клан
cancel = "SENIOR"     # Минимальный ранг участника клана, который позволяет отменить приглашение игроку в клан
kick = "COMMODORE"    # Минимальный ранг участника клана, который позволяет выгнать игрока из клана
promote = "COMMODORE" # Минимальный ранг участника клана, который позволяет повысить соклановца
donate = "RECRUIT"    # Минимальный ранг участника клана, который позволяет пополнить бюджет клана
demote = "COMMODORE"  # Минимальный ранг участника клана, который позволяет понизить соклановца
invites = "COMMODORE" # Минимальный ранг участника клана, который позволяет открыть меню приглашений в свой клан 
party = "COMMODORE"   # Минимальный ранг участника клана, который позволяет пригласить соклановцев в пати
admiral = "ADMIRAL"   # Минимальный ранг участника клана, который позволяет передать Адмирала соклановцу

[values]
games = [   # Список игр, которые будут доступные для добавления клановых очков
    "БедВарс",
    "СкайВарс",
    "Тайна Убийства",
    "МиксГейм",
    "ТНТРан",
    "Дуэли"
]

[slots.initial]
plus = 5
cost = 0.0

[slots.first]
plus = 5
cost = 15_000.0

[slots.second]
plus = 5
cost = 15_000.0

[slots.third]
plus = 5
cost = 15_000.0

[slots.fourth]
plus = 10
cost = 30_000.0

[slots.fifth]
plus = 25
cost = 75_000.0

[slots.sixth]
plus = 30
cost = 100_000.0

[ad.tariff_12]
hours = 12
cost = 60000.0

[ad.tariff_24]
hours = 24
cost = 120000.0

