[database]
host = "localhost"   # Хост
port = 3306          # Порт
user = "root"        # Пользователь
pass = "root"        # Пароль
data = "clans"       # База данных

[general]
action_expire = 30  # Время (в секундах), после которого действие отменится.

[pricing]
create = 70_000.0   # Создание клана
rename = 50_000.0   # Переименование клана

[permissions]
create = "clan.create"   # Право на создание клана

[restrictions]
min_name_length = 3    # Минимальное кол-во символов в имени клана (только буквы, без учёта цвета)
max_name_length = 12   # Максимальное кол-во символов в имени клана (только буквы, без учёта цвета)

[actions]             # RECRUIT, SENIOR, COMMODORE, ADMIRAL
rename = "ADMIRAL"    # Минимальный ранг участника клана, который позволяет переименовать клан
disband = "ADMIRAL"   # Минимальный ранг участника клана, который позволяет расформировать клан
invite = "SENIOR"     # Минимальный ранг участника клана, который позволяет пригласить игрока в клан
cancel = "SENIOR"     # Минимальный ранг участника клана, который позволяет отменить приглашение игроку в клан
kick = "COMMODORE"    # Минимальный ранг участника клана, который позволяет выгнать игрока из клана
promote = "COMMODORE" # Минимальный ранг участника клана, который позволяет повысить соклановца
donate = "RECRUIT"    # Минимальный ранг участника клана, который позволяет пополнить бюджет клана
demote = "COMMODORE"    # Минимальный ранг участника клана, который позволяет понизить соклановца

[values]
games = [   # Список игр, которые будут доступные для добавления клановых очков
    "БедВарс",
    "СкайВарс",
    "Тайна Убийства",
    "МиксГейм",
    "ТНТРан",
    "Дуэли"
]
